services:
- docker

sudo: true

install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- make build

script:
- make test

after_success:
- make push

before_deploy:
- make release

deploy:
  provider: releases
  api_key:
    secure: At2OMLvzKtItmyx+JT5w4StBfATuDIqBTN8Bmb+ekoSer7x65cD5BPe1hSMFV3w6bNs+gD9dp3z5uLyfL391TTlCxhVH5lTa5dp5Yx+VD/hE9cWQDLnvsEUIxtzXMD5mrND+v8YsvLiIOA0LPrkqRgVdP4uvsBV0BLaR9iw5uBFnMF1wZA+WS2Sg1w7OrRh1k3/9QUOdlnzzsTF+edjIOq4PTXdtMfg5LKdBKJzZsZ4NwyGhMapwJ7Z7WhyhUY+5Apsr+etiCeB47cR5xoVKcFiz13R3/9R1taLvoDnLkFWhyWVMF5Bkg4PbJ0JXFiOymzqEMoJdyZ17UuS8Ktce5y0CbJWaZfKkVtFowU/qfDqylG+LpV9XCMIgiJj8tTQjcENRLTDQEiUAcuN3KTlxizEMQ9tjkkUXHi1SDck6IXZFtLfOVBulDJ3O0WGLau0KGxKl6/LP5N1XqKDIbE40UAc5gNZkKxhwiXZk2s0NPOUORLLjgPL/p2PYal7J8NZoWyzQJIvf5xDk5nnVDBpHb2vtYjh27Ojhg1ngexghPNmErZPBImMXAxbLx/vio9j3/Zxiq/LXXTyPujaapMs13YqH8rDgodj7v/Ba3HFjxJMUSj3+gw01cMjf+DdWKQgB3OEszrGuLm1hZw/vlHevxdB1wTEK7UIfhpRMxjnKXuQ=
  file: ''
- release/goping-linux-amd64
- release/goping-linux-386
- release/goping-linux-arm
- release/goping-darwin-amd64
  skip_cleanup: true
  on:
    repo: gersongraciani/goping
    tags: true

after_deploy:
- mv Dockerfile Dockerfile.test
- cp -f Dockerfile.release Dockerfile
- ls release/*
- docker build -t gersongraciani/goping:${TRAVIS_TAG} .
- docker push gersongraciani/goping:${TRAVIS_TAG}
- docker build -t gersongraciani/goping:latest .
- docker push gersongraciani/goping:latest
- mv Dockerfile.test Dockerfile
