language: go
sudo: true
go:
  - 1.5.3
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    
install:
  - go get  github.com/smartystreets/goconvey
  - go get  -d golang.org/x/net

script: go test -v github.com/gersongraciani/goping/lab/experiment13
